services:
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      NODE_EXTRA_CA_CERTS: "/app/config/cert.pem"
    volumes:
      - type: bind
        source: ./server.ts
        target: /app/server.ts
        read_only: true
